IF EXISTS 
(
    SELECT * FROM sysdatabases WHERE NAME = 'QLGVSV'
)
DROP DATABASE QLGVSV
GO



CREATE DATABASE QLGVSV
GO

USE QLGVSV
GO

CREATE TABLE USERS
(
    username NVARCHAR(50) NOT NULL,
    password NVARCHAR(50),
    role NVARCHAR(50),

    CONSTRAINT PK_USER PRIMARY KEY (username)
)
GO

CREATE TABLE STUDENTS
(
    MSSV NVARCHAR(50) NOT NULL,
    HoTen NVARCHAR(50),
    Email NVARCHAR(50),
    SoDT NVARCHAR(50),
    Gioitinh BIT,
    Diachi NVARCHAR(50),
    Hinh NVARCHAR(50),

    CONSTRAINT PK_ST PRIMARY KEY (MSSV)
)
GO

CREATE TABLE GRADE
(
    ID int NOT NULL IDENTITY(1,1),
    MSSV NVARCHAR(50),
    Tienganh FLOAT,
    Tinhoc FLOAT,
    GDTC FLOAT,

    CONSTRAINT PK_GRADE PRIMARY KEY (ID),
    CONSTRAINT FK_GRADE_ST FOREIGN KEY (MSSV) REFERENCES STUDENTS (MSSV)
)
GO