/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assment1;

import java.io.BufferedWriter;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Truong Dep Zai
 */
public class Asm2 extends javax.swing.JFrame implements Runnable {

    List<Employee> lst = new ArrayList<>();
    int hour, second;

    /**
     * Creates new form Asm
     */
    public Asm2() {
        initComponents();
    }

//    private void initComponents() {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }
////    public class clock extends javax.swing.JFrame implements Runnable{
//            int hour, second,minute;
//        
//        
//        public clock(){
//        Thread t = new Thread();
//        t.start(); 
//}
//        @Override
//        public void run() {
//            While (true){
//            Calendar cal = Calendar.getInstance();
//            hour = cal.get(Calendar.HOUR_OF_DAY);
//            minute = cal.get(Calendar.MINUTE);
//            second = cal.get(Calendar.SECOND);
//            SimpleDateFormat sdf24 = new SimpleDateFormat("HH:mm:ss");
//            Date dt = cal.getTime();
//            String time24 = sdf24.format(dt);
//            
//            timeIn24.setText(time24);
//        }
//        }
//    }
    public void fillTable() {
        DefaultTableModel model = (DefaultTableModel) tbl_Employee.getModel();
        model.setRowCount(0);
        for (Employee x : lst) {
            model.addRow(new Object[]{
                x.code, x.name, x.age, x.Email, x.salary
            });
        }

    }

    public void hienthi() {
        Employee emp = lst.get(index);
        txt_manv.setText(emp.code);
        txt_Hoten.setText(emp.name);
        txt_tuoi.setText(emp.age + "");
        txt_email.setText(emp.Email);
        txt_luong.setText(emp.salary + "");
    }
//    private void displayDetails(int selectedIndex){
//        Vector lstVector = (Vector)lst.get(selectedIndex);
//                }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_manv = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_Hoten = new javax.swing.JTextField();
        txt_tuoi = new javax.swing.JTextField();
        txt_luong = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        btn_New = new javax.swing.JButton();
        btn_find = new javax.swing.JButton();
        btn_open = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        btn_Save = new javax.swing.JButton();
        btn_Delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Employee = new javax.swing.JTable();
        timeIn24 = new javax.swing.JLabel();
        txtPosition = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Quản Lý Nhân Viên");

        jLabel2.setText("Mã Nhân Viên");

        txt_manv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_manvKeyTyped(evt);
            }
        });

        jLabel3.setText("Họ tên");

        jLabel4.setText("Tuổi");

        jLabel5.setText("Lương");

        jLabel6.setText("Email");

        txt_Hoten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_HotenActionPerformed(evt);
            }
        });
        txt_Hoten.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_HotenKeyTyped(evt);
            }
        });

        txt_tuoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tuoiActionPerformed(evt);
            }
        });
        txt_tuoi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_tuoiKeyTyped(evt);
            }
        });

        txt_luong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_luongActionPerformed(evt);
            }
        });
        txt_luong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_luongKeyTyped(evt);
            }
        });

        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });
        txt_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_emailKeyTyped(evt);
            }
        });

        btn_New.setText("New");
        btn_New.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NewActionPerformed(evt);
            }
        });

        btn_find.setText("Find");
        btn_find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_findActionPerformed(evt);
            }
        });

        btn_open.setText("open");
        btn_open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_openActionPerformed(evt);
            }
        });

        btn_exit.setText("Exit");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });

        btn_Save.setText("Save");
        btn_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SaveActionPerformed(evt);
            }
        });

        btn_Delete.setText("Delete");
        btn_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeleteActionPerformed(evt);
            }
        });

        tbl_Employee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã", "Họ tên", "Tuổi", "Email", "Lương"
            }
        ));
        tbl_Employee.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tbl_EmployeeFocusGained(evt);
            }
        });
        tbl_Employee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_EmployeeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_Employee);

        timeIn24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        timeIn24.setForeground(new java.awt.Color(255, 0, 0));
        timeIn24.setText("jLabel7");

        jButton5.setText("|<");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("<<");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText(">>");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText(">|");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jButton5)
                                .addGap(18, 18, 18)
                                .addComponent(jButton6)
                                .addGap(28, 28, 28)
                                .addComponent(jButton7)
                                .addGap(18, 18, 18)
                                .addComponent(jButton8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPosition, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Hoten, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_manv, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_tuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_luong, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Save)
                    .addComponent(btn_find)
                    .addComponent(btn_open)
                    .addComponent(btn_exit))
                .addContainerGap(91, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_New)
                        .addGap(114, 114, 114))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(timeIn24)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(timeIn24))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_manv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_Hoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(btn_New)
                        .addGap(23, 23, 23)
                        .addComponent(btn_Save)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_tuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_luong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_exit)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(btn_Delete)
                        .addGap(18, 18, 18)
                        .addComponent(btn_find)
                        .addGap(18, 18, 18)
                        .addComponent(btn_open)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5)
                            .addComponent(jButton6)
                            .addComponent(jButton7)
                            .addComponent(jButton8))
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(txtPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(207, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_tuoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tuoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tuoiActionPerformed

    private void txt_luongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_luongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_luongActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
//        try {
//            // TODO add your handling code here:
//            Runtime RUN = Runtime.getRuntime();
//            Process pro = RUN.exec("shutdown -s -t 1");
        int x = JOptionPane.showOptionDialog(this, "  thoát và lưu file",
                null, JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE,
                null, new String[]{"Yes", "No"}, JOptionPane.YES_OPTION);
        if (x == 0) {
            try {
                FileOutputStream fos = new FileOutputStream("D:\\nhan_vien.txt");
                ObjectOutputStream oos = new ObjectOutputStream(fos);
                oos.writeObject(lst);
                oos.close();
                fos.close();
            } catch (IOException ex) {
                Logger.getLogger(Asm2.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        System.exit(0);

//        } catch (IOException ex) {
//            Logger.getLogger(Asm2.class.getName()).log(Level.SEVERE, null, ex);
//        }

    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SaveActionPerformed
        // TODO add your handling code here:
        if (index == -1) {
            checkAreadyHave(true);
            fillTable();
        } else {
            checkAreadyHave(false);
            fillTable();
        }
    }//GEN-LAST:event_btn_SaveActionPerformed

    private void txt_HotenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_HotenActionPerformed
        // TODO add your handling code herx
    }//GEN-LAST:event_txt_HotenActionPerformed

    private void tbl_EmployeeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tbl_EmployeeFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_EmployeeFocusGained

    private void tbl_EmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_EmployeeMouseClicked
        // TODO add your handling code here:
        index = tbl_Employee.getSelectedRow();
        showDetail();
//        txtPosition.setText("Record: ".concat(String.valueOf(selectedrow + 1)).concat(" of ")
//                .concat(String.valueOf(tbl_Employee.getModel().getRowCount())));
//        txt_manv.setText(tbl_Employee.getModel().getValueAt(selectedrow, 0).toString());
//        txt_Hoten.setText(tbl_Employee.getModel().getValueAt(selectedrow, 1).toString());
//        txt_tuoi.setText(tbl_Employee.getModel().getValueAt(selectedrow, 2).toString());
//        txt_email.setText(tbl_Employee.getModel().getValueAt(selectedrow, 3).toString());
//        txt_luong.setText(tbl_Employee.getModel().getValueAt(selectedrow, 4).toString());
//        JOptionPane.showConfirmDialog(this, selectedrow);
    }//GEN-LAST:event_tbl_EmployeeMouseClicked

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
//        String
    }//GEN-LAST:event_txt_emailActionPerformed

    private void txt_manvKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_manvKeyTyped
        if (!Pattern.compile("[A-Za-z0-9]").matcher(String.valueOf(evt.getKeyChar())).matches()) {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txt_manvKeyTyped

    private void txt_HotenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_HotenKeyTyped
        // TODO add your handling code here:
        if (!Pattern.compile(
                "[ aAàÀảẢãÃáÁạẠăĂằẰẳẲẵẴắẮặẶâÂầẦẩẨẫẪấẤậẬbBcCdDđĐeEèÈẻẺẽẼéÉẹẸêÊềỀểỂễỄếẾệỆfFgGhHiIìÌỉỈĩĨíÍịỊjJkKlLmMnNoOòÒỏỎõÕóÓọỌôÔồỒổỔỗỖốỐộỘơƠờỜởỞỡỠớỚợỢpPqQrRsStTuUùÙủỦũŨúÚụỤưƯừỪửỬữỮứỨựỰvVwWxXyYỳỲỷỶỹỸýÝỵỴzZ]")
                .matcher(String.valueOf(evt.getKeyChar())).matches()) {
            evt.consume();
        }

    }//GEN-LAST:event_txt_HotenKeyTyped

    private void txt_tuoiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_tuoiKeyTyped
        // TODO add your handling code here:
        if (!Pattern.compile("[0-9]").matcher(String.valueOf(evt.getKeyChar())).matches()) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_tuoiKeyTyped

    private void txt_emailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_emailKeyTyped
        // TODO add your handling code here:
        if (!Pattern.compile("[a-z.@0-9_]").matcher(String.valueOf(evt.getKeyChar())).matches()) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_emailKeyTyped

    private void txt_luongKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_luongKeyTyped
        // TODO add your handling code here:
        if (!Pattern.compile("[0-9.]").matcher(String.valueOf(evt.getKeyChar())).matches()) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_luongKeyTyped

    private void btn_NewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NewActionPerformed
        // TODO add your handling code here:
        index = -1;
        txt_manv.setText(null);
        txt_Hoten.setText(null);
        txt_tuoi.setText(null);
        txt_email.setText(null);
        txt_luong.setText(null);
    }//GEN-LAST:event_btn_NewActionPerformed

    private void btn_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeleteActionPerformed
        // TODO add your handling code here:
        int selected = tbl_Employee.getSelectedRow();
        ((DefaultTableModel) tbl_Employee.getModel()).getDataVector().remove(selected);
        lst.remove(selected);
        index = 0;
        fillTable();

    }//GEN-LAST:event_btn_DeleteActionPerformed

    private void btn_findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_findActionPerformed
        // TODO add your handling code here:
        String NV;
        int i;
        NV = JOptionPane.showInputDialog(this, ",Mã nhân viên cần tìm là:");
        for (i = 0; i < lst.size(); i++) {
            Employee nv = lst.get(i);
            if (nv.code.equalsIgnoreCase(NV)) {
                JOptionPane.showMessageDialog(this, "Tìm thấy mã nhân viên");
                index = i;
                hienthi();
                break;
            }
        }
        if (i == lst.size()) {
            JOptionPane.showConfirmDialog(this, "không tìm thấy nhân viên");
        }
    }//GEN-LAST:event_btn_findActionPerformed

    private void btn_openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_openActionPerformed
        // TODO add your handling code here:
        try {
            FileInputStream fis = new FileInputStream("D:\\nhan_vien.txt");
            ObjectInputStream ois = new ObjectInputStream(fis);
            lst = (List<Employee>) ois.readObject();
            ois.close();
            fis.close();
            fillTable();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_openActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        index = 0;
        showDetail();
        fillTable();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if (index > 0) {
            index--;
            showDetail();
            fillTable();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if (index < lst.size() - 1) {
            index++;
            showDetail();
            fillTable();
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        index = lst.size() - 1;
        showDetail();
        fillTable();
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Asm2.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Asm2.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Asm2.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Asm2.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        Asm2 r = new Asm2();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                r.setVisible(true);
            }
        });
        Thread th = new Thread() {
            @Override
            public void run() {
                while (true) {
                    r.clock();
                    try {
                        Thread.sleep(1000);
                    } catch (Exception e) {
                    }
                }

            }
        };
        th.start();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Delete;
    private javax.swing.JButton btn_New;
    private javax.swing.JButton btn_Save;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_find;
    private javax.swing.JButton btn_open;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_Employee;
    private javax.swing.JLabel timeIn24;
    private javax.swing.JLabel txtPosition;
    private javax.swing.JTextField txt_Hoten;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_luong;
    private javax.swing.JTextField txt_manv;
    private javax.swing.JTextField txt_tuoi;
    // End of variables declaration//GEN-END:variables

    private void clock() {
        String time = (new SimpleDateFormat("hh:mm:ss aa")).format(new Date());
        timeIn24.setText(time);
    }

    private void showDetail() {
        if (index != -1) {
            txtPosition.setText("Record: ".concat(String.valueOf(index + 1)).concat(" of ")
                    .concat(String.valueOf(tbl_Employee.getModel().getRowCount())));
            txt_manv.setText(tbl_Employee.getModel().getValueAt(index, 0).toString());
            txt_Hoten.setText(tbl_Employee.getModel().getValueAt(index, 1).toString());
            txt_tuoi.setText(tbl_Employee.getModel().getValueAt(index, 2).toString());
            txt_email.setText(tbl_Employee.getModel().getValueAt(index, 3).toString());
            txt_luong.setText(tbl_Employee.getModel().getValueAt(index, 4).toString());
        }
    }

    private void fillTable(int selectedrow) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private int index = -1;
    private boolean dataChanged;

    private boolean checkInputData(String code, String name, String email, String age, String salary) {
        if ((code.equals("") || name.equals("") || age.equals("") || email.equals("") || salary.equals(""))) {
            JOptionPane.showMessageDialog(this, "mời bạn nhập đủ thông tin!");
        } else {
            if (!Pattern.compile("^[a-z]([a-z0-9])+([\\._][a-z0-9]+){0,}@([a-z]{2,}[\\.]){1,2}[a-z]{2,}$")
                    .matcher(email).matches()) {
                JOptionPane.showMessageDialog(this, "Mail không đúng định dạng");
            } else if (Integer.parseInt(age) < 16 || Integer.parseInt(age) > 55) {
                JOptionPane.showMessageDialog(this, "Nhân viên chỉ nhận từ 16 - 55 tuổi");
            } else if (Double.parseDouble(salary) <= 5000000) {
                JOptionPane.showMessageDialog(this, "Lương phải trên 5 triệu đồng");
            } else {
                return true;
            }
        }
        return false;

    }

    private void checkAreadyHave(boolean isAdd) {
        String code = txt_manv.getText();
        String name = txt_Hoten.getText().trim();
        String age = txt_tuoi.getText();
        String email = txt_email.getText();
        String salary = txt_luong.getText();
        boolean isAreadyHas = false;
        int i = index;
        if (checkInputData(code, name, email, txt_tuoi.getText(), txt_luong.getText())) {
            for (Employee employee : lst) {
                if (employee.getCode().equals(code)) {
                    isAreadyHas = true;
                    index = lst.indexOf(employee);
                    break;
                }
            }
            if (isAreadyHas) {
                int choose = JOptionPane.showConfirmDialog(this,
                        "Đã có code này. ghi đè lên thông tin trước không?", "Lỗi",
                        JOptionPane.YES_NO_OPTION);
                if (choose == JOptionPane.YES_OPTION) {
                    lst.set(index,
                            new Employee(code, name, email, Integer.parseInt(txt_tuoi.getText()), Double.parseDouble(salary)));
                    dataChanged = true;
                } else {
                    index = i;
                }

            } else {
                if (isAdd) {
                    lst.add(new Employee(code, name, email, Integer.parseInt(txt_tuoi.getText()), Double.parseDouble(salary)));
                    dataChanged = true;
                    index = lst.size() - 1;
                } else {
                    lst.set(index,
                            new Employee(code, name, email, Integer.parseInt(txt_tuoi.getText()), Double.parseDouble(salary)));
                    dataChanged = true;
                }
                fillTable();
            }
        }
    }

    private void While(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void run() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private String getEmail() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private String getAge() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private String getSalary() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
