/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Helper.EmployerHelper;
import Model.Employee;
import java.awt.event.KeyEvent;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.event.InternalFrameAdapter;
import javax.swing.event.InternalFrameEvent;

/**
 *
 * @author ma-user
 */
public class DN extends javax.swing.JInternalFrame {

    /**
     * Creates new form DN
     */
    public DN() {
        initComponents();
        setClosable(true);
//        addInternalFrameListener(new InternalFrameAdapter() {
//            @Override
//            public void internalFrameClosed(InternalFrameEvent e) {
//                Main.showMDI();
//            }
//        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnDN = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        lblForgot = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Tên Đăng Nhập");

        txtUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUserKeyPressed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Mật Khẩu");

        btnDN.setText("Đăng Nhập");
        btnDN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDNActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        lblForgot.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblForgot.setForeground(new java.awt.Color(0, 51, 255));
        lblForgot.setText("Quên Mật Khẩu ?");
        lblForgot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblForgotMouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Secure.png"))); // NOI18N

        txtPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPassKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUser)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblForgot)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPass)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDN, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(4, 4, 4)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDN)
                    .addComponent(btnReset)
                    .addComponent(btnHuy))
                .addGap(32, 32, 32)
                .addComponent(lblForgot)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtUser.setText("");
        txtPass.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void lblForgotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblForgotMouseClicked
        // TODO add your handling code here:
        try {
//            for (JInternalFrame chiFrame : Main.rootPanel.getAllFrames()) {
//                chiFrame.dispose();
//            }
            Main.qmk = new QMK();
            Main.qmk.setTitle("Quên mật khẩu");
            Main.rootPanel.add(Main.qmk);
            Main.qmk.setLocation(Main.rootPanel.getWidth() / 2 - Main.qmk.getWidth() / 2,
                    (Main.rootPanel.getHeight() - 20) / 2 - Main.qmk.getHeight() / 2 - 20);
            Main.qmk.setVisible(true);
//            Main.qmk.addInternalFrameListener(new InternalFrameAdapter() {
//                @Override
//                public void internalFrameClosed(InternalFrameEvent e) {
//                    try {
//                        for (JInternalFrame chiFrame : Main.rootPanel.getAllFrames()) {
//                            chiFrame.dispose();
//                        }
//
//                        if (Main.dn == null || Main.dn.isClosed()) {
//                            Main.dn = new DN();
//                            Main.dn.setTitle("Đăng Nhập");
//                            Main.rootPanel.add(Main.dn);
//                            Main.dn.setLocation(Main.rootPanel.getWidth() / 2 - Main.dn.getWidth() / 2,
//                                    (Main.rootPanel.getHeight() - 20) / 2 - Main.dn.getHeight() / 2 - 20);
//                            Main.dn.setVisible(true);
//                        } else {
//                            Main.dn.setLocation(Main.rootPanel.getWidth() / 2 - Main.dn.getWidth() / 2,
//                                    (Main.rootPanel.getHeight() - 20) / 2 - Main.dn.getHeight() / 2 - 20);
//                            Main.dn.setVisible(true);
//                        }
//                        Main.dn.addInternalFrameListener(new InternalFrameAdapter() {
//                            @Override
//                            public void internalFrameClosed(InternalFrameEvent e) {
//                                if (Main.logged == false) {
//                                    System.exit(0);
//                                }
//                            }
//                        });
//                    } catch (Exception ex) {
//                        try {
//                            FileWriter fw = new FileWriter(System.getProperty("user.dir") + "log/log.txt", true);
//                            BufferedWriter bw = new BufferedWriter(fw);
//                            PrintWriter out = new PrintWriter(bw);
//                            ex.printStackTrace(out);
//                        } catch (IOException IOE) {
//                        }
//                    }
//                }
//            });
        } catch (Exception e) {
            try {
                FileWriter fw = new FileWriter(System.getProperty("user.dir") + "log/log.txt", true);
                BufferedWriter bw = new BufferedWriter(fw);
                PrintWriter out = new PrintWriter(bw);
                e.printStackTrace(out);
            } catch (IOException ex) {
            }
        }
    }//GEN-LAST:event_lblForgotMouseClicked

    private void btnDNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDNActionPerformed
        // TODO add your handling code here:
        login();
    }//GEN-LAST:event_btnDNActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnHuyActionPerformed

    private void txtUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            login();
        }
    }//GEN-LAST:event_txtUserKeyPressed

    private void txtPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            login();
        }
    }//GEN-LAST:event_txtPassKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDN;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblForgot;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables

    private void login() {
        if (txtUser.getText().isEmpty() || (new String(txtPass.getPassword())).isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mời nhập đầy đủ tên đăng nhập và mật khẩu");
        } else {
            Main.user = EmployerHelper.getEmployee(txtUser.getText(), new String(txtPass.getPassword()));
            if (Main.user.getPosition() != null) {
                Main.logged = true;
                JOptionPane.showMessageDialog(this, "Đăng nhập thành công");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Sai tên đăng nhập hoặc mật khẩu.");
            }
        }
    }
}
