/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;


import Uhelper.ClassHoaDon;
import Uhelper.Helper;
import Uhelper.TheModel;
import java.awt.Image;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author khanh
 */
public class LichSuHoaDon extends javax.swing.JInternalFrame {

    /**
     * Creates new form LichSuHoaDon
     */
    Connection cn;
    DefaultTableModel model;
    ArrayList<ClassHoaDon> lsthoadon = new ArrayList<>();
    int index;

    public LichSuHoaDon() {
        initComponents();
        cn = Helper.ketnoi("QLBH01");
        String[] columnName = {"Mã hóa đơn", "Ảnh sản phẩm", "Tên sản phẩm", "Số lượng", "Đơn giá", "Thành tiền", "Ngày tạo", "Nhân viên"};
        try {
            String sql = "SELECT hoadon.mahd,anh,hoadonchitiet.tensp,hoadonchitiet.soluong,hoadonchitiet.dongia,thanhtien,ngaytao,tentaikhoan\n"
                    + "FROM ((dbo.hoadonchitiet JOIN dbo.hoadon ON hoadonchitiet.mahd = hoadon.mahd)\n"
                    + "JOIN dbo.sanpham ON sanpham.maspchitiet = hoadonchitiet.maspchitiet)\n"
                    + "ORDER BY hoadonchitiet.mahd desc";
            Statement stm = cn.createStatement();
            ResultSet rs = stm.executeQuery(sql);
            while (rs.next()) {
                String mahd = rs.getString(1);
                String anh = rs.getString(2);
                String tensp = rs.getString(3);
                String soluong = rs.getString(4) + "";
                String dongia = rs.getFloat(5) + "00";
                String thanhtien = rs.getFloat(6) + "00";
                String ngaytao = rs.getString(7);
                String tentk = rs.getString(8);
                lsthoadon.add(new ClassHoaDon(mahd, anh, tensp, soluong, dongia, thanhtien, ngaytao, tentk));
//                lsthoadon.add(new ClassHoaDon(mahd,anh,tensp,soluong,dongia,thanhtien,ngaytao,tentk));
            }
            stm.close();
            rs.close();
        } catch (Exception e) {
        }
        Object[][] rows = new Object[lsthoadon.size()][8];
        for (int i = 0; i < lsthoadon.size(); i++) {
            rows[i][0] = lsthoadon.get(i).getMaspct();
            if (lsthoadon.get(i).getAnh() != null) {
                ImageIcon icon1 = new ImageIcon("src//Image//" + lsthoadon.get(i).getAnh());
                Image im = icon1.getImage();
                ImageIcon icon = new ImageIcon(im.getScaledInstance(100, 100, Image.SCALE_SMOOTH));
                rows[i][1]=icon;
            } else {
                rows[i][1]=null;
            }
            rows[i][2] = lsthoadon.get(i).getTen();
            rows[i][3] = lsthoadon.get(i).getSoluong();
            rows[i][4] = lsthoadon.get(i).getDongia();
            rows[i][5] = lsthoadon.get(i).getThanhtien();
            rows[i][6] = lsthoadon.get(i).getNgaytao();
            rows[i][7] = lsthoadon.get(i).getNguoitao();
        }
        TheModel model=new TheModel(rows,columnName);
        tbl_lichsu.setModel(model);
        tbl_lichsu.setRowHeight(100);
        tbl_lichsu.getColumnModel().getColumn(1).setPreferredWidth(100);
//        loadTable();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_lichsu = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        tbl_lichsu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbl_lichsu);

        jLabel1.setForeground(new java.awt.Color(51, 0, 204));
        jLabel1.setText("Quay lại");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jLabel1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_lichsu;
    // End of variables declaration//GEN-END:variables
}
