/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

import Uhelper.Danhmuc;
import Uhelper.Helper;
import com.sun.java.swing.plaf.windows.resources.windows;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class QL_DanhMuc extends javax.swing.JInternalFrame {

    /**
     * Creates new form QL_DanhMuc
     */
    Connection con = Helper.ketnoi("QLBH01");

    String[] header = {"Loại", "Tên danh mục"};
    String data[][] = null;
    
    DefaultTableModel model = new DefaultTableModel(data, header);
//    QL_DanhMuc quanlydanhmuc;
    ThemDanhMuc themdanhmuc;
  
    public QL_DanhMuc() {
        initComponents();
         loadDataToList();
        loadDataToTable();
       

    }
    public void loadDataToList(){
        
    }
    public void loadDataToTable() {
        try {
//            DefaultTableModel model = (DefaultTableModel) tbl_danhmuc.getModel();
            String sql = "select * from danhmuc  where loai like '%gi%' ";
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery(sql);
            model.setRowCount(0);
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString(2));
                v.add(rs.getString(1));
                model.addRow(v);
            }
//            themdanhmuc.show();
//            themdanhmuc.listDanhmuc.add();
            
            tbl_danhmuc.setModel(model);
             windows.clearCache();
            rs.close();
            stm.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi Load data to table danh muc ");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dsk = new javax.swing.JDesktopPane();
        btn_xoa = new javax.swing.JButton();
        btn_them = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_danhmuc = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        dsk.setBackground(new java.awt.Color(255, 255, 255));
        dsk.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dsk.setPreferredSize(new java.awt.Dimension(1193, 524));

        btn_xoa.setText("Xóa danh mục");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        btn_them.setText("Thêm danh mục");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        tbl_danhmuc.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tbl_danhmuc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbl_danhmuc);

        dsk.setLayer(btn_xoa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dsk.setLayer(btn_them, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dsk.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dskLayout = new javax.swing.GroupLayout(dsk);
        dsk.setLayout(dskLayout);
        dskLayout.setHorizontalGroup(
            dskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dskLayout.createSequentialGroup()
                .addGap(443, 443, 443)
                .addGroup(dskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(dskLayout.createSequentialGroup()
                        .addComponent(btn_them)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_xoa))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(480, Short.MAX_VALUE))
        );
        dskLayout.setVerticalGroup(
            dskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dskLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(dskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_them)
                    .addComponent(btn_xoa))
                .addGap(147, 147, 147))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dsk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1375, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dsk, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
        int check = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa danh mục này không ?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (check == JOptionPane.YES_OPTION) {
            try {
                String x = "Đã Xóa";
                int row = tbl_danhmuc.getSelectedRow();
                String sql = "update danhmuc set loai=? where tendanhmuc = ?";
                PreparedStatement pstm = con.prepareStatement(sql);
                pstm.setString(1, x);
                pstm.setString(2, tbl_danhmuc.getValueAt(row, 1).toString());
                int check2 = pstm.executeUpdate();
                if (check2 > 0) {
//                    themdanhmuc.show();
                    loadDataToTable();
                    JOptionPane.showMessageDialog(this, "Đã xóa thành công");
                } else {
                    JOptionPane.showMessageDialog(this, "Lỗi không xóa được ");
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Lỗi ");
            }
        } else {

        }
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed

//        QL_DanhMuc qldm = new QL_DanhMuc();
        ThemDanhMuc tdm = new ThemDanhMuc();
        dsk.add(tdm);
        tdm.setVisible(true);
        loadDataToTable();

    }//GEN-LAST:event_btn_themActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        loadDataToTable();
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JDesktopPane dsk;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_danhmuc;
    // End of variables declaration//GEN-END:variables
}
