/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

import Uhelper.ClassSanPham;
import Uhelper.Helper;
import Uhelper.TheModel1;
import Uhelper.TheModel2;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class Sanpham1 extends javax.swing.JInternalFrame {

    int index;
    Connection cn;
    ThongTinSanPham ttsp;
    ArrayList<ClassSanPham> lstsanpham = new ArrayList<>();

    /**
     * Creates new form Sanpham1
     */
    public Sanpham1() {
        initComponents();
        String[] columnName = {"Mã sản phẩm chi tiết", "Tên sản phẩm", "Danh mục", "Kích cỡ", "Số lượng", "Đơn giá", "Mô tả", "Ảnh"};
        cn = Helper.ketnoi("QLBH01");
//        LoadTable();
        addcboLoaisp();

    }

    public void addcboLoaisp() {
        //load cbo_khoahoc
        try {
            cn = Helper.ketnoi("QLBH01");
            String sql = "select distinct loai from danhmuc  where loai like '%gi%'";
            Statement stm = cn.createStatement();
            ResultSet rs = stm.executeQuery(sql);
            while (rs.next()) {
                cbo_Loai.addItem(rs.getString(1));
            }
            stm.close();
            rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi load to CBOCD");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_sanpham = new javax.swing.JTable();
        cbo_danhmuc = new javax.swing.JComboBox<>();
        cbo_Loai = new javax.swing.JComboBox<>();

        tbl_sanpham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbl_sanpham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_sanphamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_sanpham);

        cbo_danhmuc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbo_danhmucItemStateChanged(evt);
            }
        });

        cbo_Loai.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbo_LoaiItemStateChanged(evt);
            }
        });

        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(cbo_danhmuc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(cbo_Loai, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(cbo_Loai, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 594, Short.MAX_VALUE)
                .addComponent(cbo_danhmuc, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(259, 259, 259))
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1364, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(179, Short.MAX_VALUE)))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbo_Loai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbo_danhmuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(451, Short.MAX_VALUE))
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                    .addContainerGap(104, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbo_LoaiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbo_LoaiItemStateChanged
        // TODO add your handling code here:
        try {

            String sql = "select distinct tendanhmuc from danhmuc where loai = ?";
            PreparedStatement pstm = cn.prepareStatement(sql);
            pstm.setString(1, (String) cbo_Loai.getSelectedItem());
            ResultSet rs = pstm.executeQuery();
            cbo_danhmuc.removeAllItems();
            while (rs.next()) {
                cbo_danhmuc.addItem(rs.getString(1));
            }
            pstm.close();
            rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi statechange CBLOAI");
        }
    }//GEN-LAST:event_cbo_LoaiItemStateChanged

    private void cbo_danhmucItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbo_danhmucItemStateChanged
//         TODO add your handling code here:
        String[] columnName = {"Mã sản phẩm chi tiết", "Tên sản phẩm", "Danh mục", "Kích cỡ", "Số lượng", "Đơn giá", "Mô tả", "Ảnh"};
        try {
            String sql = "select maspchitiet,tensp, sanpham.tendanhmuc ,kichco, soluong,dongia,mota,anh from sanpham \n"
                    + "join danhmuc on sanpham.tendanhmuc = danhmuc.tendanhmuc\n"
                    + "where sanpham.tendanhmuc = ?";
            PreparedStatement pstm = cn.prepareStatement(sql);
            pstm.setString(1, (String) cbo_danhmuc.getSelectedItem());
            ResultSet rs = pstm.executeQuery();
            lstsanpham.clear();
            while (rs.next()) {
                lstsanpham.add(new ClassSanPham(rs.getString(1), rs.getString(2), rs.getString(3),
                        rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7), rs.getString(8)));
            }
            Object[][] rows = new Object[lstsanpham.size()][8];
            if(lstsanpham.size()>0){
                for (int i = 0; i < lstsanpham.size(); i++) {
                rows[i][0] = lstsanpham.get(i).getMaspct();
                rows[i][1] = lstsanpham.get(i).getTensp();
                rows[i][2] = lstsanpham.get(i).getDanhmuc();
                rows[i][3] = lstsanpham.get(i).getKichco();
                rows[i][4] = lstsanpham.get(i).getSoluong();
                rows[i][5] = lstsanpham.get(i).getDongia();
                rows[i][6] = lstsanpham.get(i).getMota();
                if (lstsanpham.get(i).getAnh() != null) {
                    ImageIcon icon1 = new ImageIcon("src/Image/" + lstsanpham.get(i).getAnh());
                    Image im = icon1.getImage();
                    ImageIcon icon = new ImageIcon(im.getScaledInstance(100, 100, Image.SCALE_SMOOTH));
                    rows[i][7] = icon;
                } else {
                    rows[i][7] = null;
                }
                    

            }
            }else{
                tbl_sanpham.clearSelection();
            }
            TheModel2 model = new TheModel2(rows, columnName);
                    tbl_sanpham.setModel(model);
                    tbl_sanpham.setRowHeight(100);
                    tbl_sanpham.getColumnModel().getColumn(1).setPreferredWidth(100);
            
            pstm.close();
            rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi statechange danh mục");
        }
    }//GEN-LAST:event_cbo_danhmucItemStateChanged

    private void tbl_sanphamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_sanphamMouseClicked
        // TODO add your handling code here:
        int row = tbl_sanpham.getSelectedRow();
        if (row != -1) {
            String maspchitiet = (String) tbl_sanpham.getValueAt(row, 0);
            ttsp = new ThongTinSanPham(maspchitiet);
            jDesktopPane1.add(ttsp);
            ttsp.setVisible(true);
        }
    }//GEN-LAST:event_tbl_sanphamMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbo_Loai;
    private javax.swing.JComboBox<String> cbo_danhmuc;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_sanpham;
    // End of variables declaration//GEN-END:variables
}
