/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

import Uhelper.Helper;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class ThongTinSanPham extends javax.swing.JInternalFrame {

    /**
     * Creates new form ThongTinSanPham
     */
    Connection con;

    public ThongTinSanPham(String maspchitiet) {
        initComponents();
        con = Helper.ketnoi("QLBH01");
        
        load_data(maspchitiet);
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void upload(String hinh) {
        ImageIcon img = new ImageIcon("src//Image//" + hinh);
        Image im = img.getImage();
        ImageIcon icon = new ImageIcon(im.getScaledInstance(200,200, im.SCALE_SMOOTH));
        lbl_anh.setIcon(icon);

    }

    public void load_data(String maspct) {
        try {
            String sql = "select * from sanpham where maspchitiet=?";
            PreparedStatement pstm = con.prepareStatement(sql);
            pstm.setString(1, maspct);
            ResultSet rs = pstm.executeQuery();
            while (rs.next()) {
                txt_masp.setText(rs.getString(1));
                txt_maspchitiet.setText(rs.getString(2));
                txt_tensp.setText(rs.getString(3));
                txt_danhmuc.setText(rs.getString(4));
                cbo_kichco.setSelectedItem(rs.getString(5));
                cbo_mausac.setSelectedItem(rs.getString(6));
                txt_soluong.setText(rs.getString(7));
                txt_dongia.setText(rs.getString(8));
                txt_ngaythem.setText(rs.getString(9));
                txt_mota.setText(rs.getString(10));
                upload(rs.getString(11));
                String trangthai = rs.getString(12);
                if (trangthai.equals("1")) {
                    txt_trangthai.setText("Tồn tại");
                } else {
                    txt_trangthai.setText("Đã xóa");
                }
            }
        } catch (Exception e) {
//            e.printStackTrace();
        }
    }

    public void loadData() {
        try {
            String sql = "select kichco,mausac from sanpham where masp =? ";
            PreparedStatement pstm = con.prepareStatement(sql);
            pstm.setString(1, txt_masp.getText());
            ResultSet rs = pstm.executeQuery();
            while (rs.next()) {
                cbo_kichco.addItem(rs.getString(1));
                cbo_mausac.addItem(rs.getString(2));
            }
        } catch (Exception e) {
//            e.printStackTrace();
        }

    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_masp = new javax.swing.JTextField();
        txt_maspchitiet = new javax.swing.JTextField();
        txt_soluong = new javax.swing.JTextField();
        txt_dongia = new javax.swing.JTextField();
        txt_ngaythem = new javax.swing.JTextField();
        lbl_anh = new javax.swing.JLabel();
        txt_trangthai = new javax.swing.JTextField();
        cbo_kichco = new javax.swing.JComboBox<>();
        cbo_mausac = new javax.swing.JComboBox<>();
        txt_danhmuc = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_tensp = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_mota = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("THÔNG TIN SẢN PHẨM");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Mã sản phẩm");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Mã sản phẩm chi tiết ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Tên sản phẩm");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Tên danh mục");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Kích cỡ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Màu sắc");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Số lượng");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Đơn giá");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Ngày thêm");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Mô tả");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Ảnh");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Trạng thái");

        txt_trangthai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_trangthaiActionPerformed(evt);
            }
        });

        cbo_kichco.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbo_kichcoItemStateChanged(evt);
            }
        });

        cbo_mausac.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbo_mausacItemStateChanged(evt);
            }
        });

        txt_tensp.setColumns(20);
        txt_tensp.setRows(5);
        jScrollPane1.setViewportView(txt_tensp);

        txt_mota.setColumns(20);
        txt_mota.setLineWrap(true);
        txt_mota.setRows(5);
        txt_mota.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txt_mota);

        jLabel14.setForeground(new java.awt.Color(0, 0, 204));
        jLabel14.setText("Quay lại");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(601, 601, 601))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(cbo_kichco, 0, 223, Short.MAX_VALUE)
                                        .addComponent(txt_masp, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(txt_maspchitiet, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbo_mausac, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5)
                            .addComponent(jLabel11)
                            .addComponent(jLabel9))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_danhmuc)
                            .addComponent(txt_dongia, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(txt_soluong))
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(jLabel10))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_ngaythem, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_trangthai, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_anh, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel14))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_danhmuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txt_ngaythem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txt_masp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_anh, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txt_soluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(txt_maspchitiet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_dongia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel4))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel13)
                                            .addComponent(txt_trangthai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(31, 31, 31))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(132, 132, 132)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel6)
                                            .addComponent(cbo_kichco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(26, 26, 26)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel7)
                                            .addComponent(cbo_mausac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbo_kichcoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbo_kichcoItemStateChanged
        // TODO add your handling code here:
        try {
            String sql = "select * from sanpham where masp=? and kichco=?";
            PreparedStatement pstm = con.prepareStatement(sql);
            pstm.setString(1, txt_masp.getText());
            pstm.setString(2, (String) cbo_kichco.getSelectedItem());
            ResultSet rs = pstm.executeQuery();
            while (rs.next()) {

                txt_maspchitiet.setText(rs.getString(2));
                txt_tensp.setText(rs.getString(3));
                txt_danhmuc.setText(rs.getString(4));

                cbo_mausac.setSelectedItem(rs.getString(6));
                txt_soluong.setText(rs.getString(7));
                txt_dongia.setText(rs.getString(8));
                txt_ngaythem.setText(rs.getString(9));
                txt_mota.setText(rs.getString(10));
                upload(rs.getString(11));
                String trangthai = rs.getString(12);
                if (trangthai.equals("1")) {
                    txt_trangthai.setText("Tồn tại");
                } else {
                    txt_trangthai.setText("Đã xóa");
                }
            }
        } catch (Exception e) {
//            e.printStackTrace();
        }
    }//GEN-LAST:event_cbo_kichcoItemStateChanged

    private void cbo_mausacItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbo_mausacItemStateChanged
        // TODO add your handling code here:
        try {
            String sql = "select * from sanpham where masp=? and kichco=?";
            PreparedStatement pstm = con.prepareStatement(sql);
            pstm.setString(1, txt_masp.getText());
            pstm.setString(2, (String) cbo_kichco.getSelectedItem());
            ResultSet rs = pstm.executeQuery();
            while (rs.next()) {

                txt_maspchitiet.setText(rs.getString(2));
                txt_tensp.setText(rs.getString(3));
                txt_danhmuc.setText(rs.getString(4));

                cbo_kichco.setSelectedItem(rs.getString(6));
                txt_soluong.setText(rs.getString(7));
                txt_dongia.setText(rs.getString(8));
                txt_ngaythem.setText(rs.getString(9));
                txt_mota.setText(rs.getString(10));
                upload(rs.getString(11));
                String trangthai = rs.getString(12);
                if (trangthai.equals("1")) {
                    txt_trangthai.setText("Tồn tại");
                } else {
                    txt_trangthai.setText("Đã xóa");
                }
            }
        } catch (Exception e) {
//            e.printStackTrace();
        }
    }//GEN-LAST:event_cbo_mausacItemStateChanged

    private void txt_trangthaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_trangthaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_trangthaiActionPerformed

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jLabel14MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbo_kichco;
    private javax.swing.JComboBox<String> cbo_mausac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_anh;
    private javax.swing.JTextField txt_danhmuc;
    private javax.swing.JTextField txt_dongia;
    private javax.swing.JTextField txt_masp;
    private javax.swing.JTextField txt_maspchitiet;
    private javax.swing.JTextArea txt_mota;
    private javax.swing.JTextField txt_ngaythem;
    private javax.swing.JTextField txt_soluong;
    private javax.swing.JTextArea txt_tensp;
    private javax.swing.JTextField txt_trangthai;
    // End of variables declaration//GEN-END:variables
}
