/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

import Uhelper.Helper;
import Uhelper.Sanpham;
import Uhelper.TheModel1;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class TimKiem extends javax.swing.JInternalFrame {

    /**
     * Creates new form TimKiem
     */
    Connection con;
    ThongTinSanPham ttsp;

    public TimKiem(ArrayList<Sanpham> list) {
        initComponents();
        con = Helper.ketnoi("QLBH01");
        String[] columnName = {"Masp", "Maspchitiet", "Tên sản phẩm", "Tên danh mục", "Kích cỡ", "Màu sắc", "Số lượng",
            "Đơn giá", "Ngày thêm", "Mô tả", "Ảnh", "Trạng thái"};
        Object[][] rows = new Object[list.size()][12];
        try {
            for (int i = 0; i < list.size(); i++) {
                String sql = "Select * from sanpham where  maspchitiet=? ";
                PreparedStatement pstm = con.prepareStatement(sql);

                pstm.setString(1, list.get(i).getMaspchitet());

                ResultSet rs = pstm.executeQuery();
                while (rs.next()) {

                    rows[i][0] = rs.getString(1);
                    rows[i][1] = rs.getString(2);
                    rows[i][2] = rs.getString(3);
                    rows[i][3] = rs.getString(4);
                    rows[i][4] = rs.getString(5);
                    rows[i][5] = rs.getString(6);
                    rows[i][6] = rs.getString(7);
                    rows[i][7] = rs.getString(8);
                    rows[i][8] = rs.getString(9);
                    rows[i][9] = rs.getString(10);
                    if (rs.getString(11) != null) {
                        ImageIcon icon1 = new ImageIcon("src//Image//" + rs.getString(11));
                        Image im = icon1.getImage();
                        ImageIcon icon = new ImageIcon(im.getScaledInstance(100, 100, Image.SCALE_SMOOTH));
                        rows[i][10] = icon;
                    } else {
                        rows[i][10] = null;
                    }
                    String trangthai = "";
                    if (rs.getString(12).equalsIgnoreCase("1")) {
                        rows[i][11] = "Tồn tại";
                    } else {
                        rows[i][11] = "Đã xóa";
                    }
                    TheModel1 model1 = new TheModel1(rows, columnName);
                    tbl_timkiem.setModel(model1);
                    tbl_timkiem.setRowHeight(100);
                    tbl_timkiem.getColumnModel().getColumn(1).setPreferredWidth(100);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi load data to table");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_timkiem = new javax.swing.JTable();

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("KẾT QUẢ TÌM KIẾM");

        tbl_timkiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbl_timkiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_timkiemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_timkiem);

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(640, 640, 640)
                .addComponent(jLabel1)
                .addContainerGap(570, Short.MAX_VALUE))
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1384, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 280, Short.MAX_VALUE)))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addContainerGap(446, Short.MAX_VALUE))
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                    .addGap(0, 99, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_timkiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_timkiemMouseClicked
        // TODO add your handling code here:
        int row = tbl_timkiem.getSelectedRow();
        String maspchitiet = (String) tbl_timkiem.getValueAt(row, 1);
        ttsp = new ThongTinSanPham(maspchitiet);
        jDesktopPane1.add(ttsp);
        ttsp.setVisible(true);
    }//GEN-LAST:event_tbl_timkiemMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_timkiem;
    // End of variables declaration//GEN-END:variables
}
