/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

//import java.awt.Image;
import Uhelper.Helper;
import Uhelper.Sanpham;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;

//import javax.swing.ImageIcon;
/**
 *
 * @author Dell
 */
public class TrangchuNV extends javax.swing.JFrame {

    String hinh = "banner.png";
    Banhang bh;
    GioiThieu gt;
    Sanpham1 sp;
    ThongTinTaiKhoan_QuanLy tttk;
    /**
     * Creates new form TrangchuNV
     */
    String tentk = "";
    TimKiem tk;
    Connection con;
    ArrayList<Sanpham> list = new ArrayList<>();

    public TrangchuNV() {
        initComponents();
//        upHinh(hinh);
        tentk = DangNhap.tkdadn;
        con = Helper.ketnoi("QLBH01");

        sp = new Sanpham1();
        gt = new GioiThieu();
        bh = new Banhang();
        tk = new TimKiem(list);
//        this.setExtendedState(TrangchuNV.MAXIMIZED_BOTH);
        tttk = new ThongTinTaiKhoan_QuanLy(tentk);

    }

//    public void upHinh(String hinh) {
//        ImageIcon image = new ImageIcon("src//Images//" + hinh);
//        Image img = image.getImage();
//        ImageIcon icon = new ImageIcon(img.getScaledInstance(png_banner.getWidth(), png_banner.getHeight(), img.SCALE_SMOOTH));
//        lbl_banner.setIcon(icon);
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        destop = new javax.swing.JDesktopPane();
        lbl_banner = new javax.swing.JLabel();
        txt_timkiem = new javax.swing.JTextField();
        btn_timkiem = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menu_trangchu = new javax.swing.JMenu();
        menu_sanpham = new javax.swing.JMenu();
        menu_banhang = new javax.swing.JMenu();
        menu_gioithieu = new javax.swing.JMenu();
        menu_taikhoan = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_banner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/banner.png"))); // NOI18N
        lbl_banner.setPreferredSize(new java.awt.Dimension(1193, 524));

        destop.setLayer(lbl_banner, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout destopLayout = new javax.swing.GroupLayout(destop);
        destop.setLayout(destopLayout);
        destopLayout.setHorizontalGroup(
            destopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, destopLayout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addComponent(lbl_banner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );
        destopLayout.setVerticalGroup(
            destopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(destopLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbl_banner, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        btn_timkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image11/find.png"))); // NOI18N
        btn_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timkiemActionPerformed(evt);
            }
        });

        jMenu1.setForeground(new java.awt.Color(0, 204, 204));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo_giay.png"))); // NOI18N
        jMenuBar1.add(jMenu1);

        menu_trangchu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image11/home.png"))); // NOI18N
        menu_trangchu.setText("Trang chủ");
        menu_trangchu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_trangchuMouseClicked(evt);
            }
        });
        jMenuBar1.add(menu_trangchu);

        menu_sanpham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image11/Sản phẩm_box.png"))); // NOI18N
        menu_sanpham.setText("Sản Phẩm");
        menu_sanpham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_sanphamMouseClicked(evt);
            }
        });
        menu_sanpham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_sanphamActionPerformed(evt);
            }
        });
        jMenuBar1.add(menu_sanpham);

        menu_banhang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image11/bill.png"))); // NOI18N
        menu_banhang.setText("Bán Hàng");
        menu_banhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_banhangMouseClicked(evt);
            }
        });
        menu_banhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_banhangActionPerformed(evt);
            }
        });
        jMenuBar1.add(menu_banhang);

        menu_gioithieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image11/Giới thiệu_iocn.png"))); // NOI18N
        menu_gioithieu.setText("Giới Thiệu");
        menu_gioithieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_gioithieuMouseClicked(evt);
            }
        });
        menu_gioithieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_gioithieuActionPerformed(evt);
            }
        });
        jMenuBar1.add(menu_gioithieu);

        menu_taikhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/userss.png"))); // NOI18N
        menu_taikhoan.setMargin(new java.awt.Insets(0, 680, 0, 0));
        menu_taikhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_taikhoanMouseClicked(evt);
            }
        });
        menu_taikhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_taikhoanActionPerformed(evt);
            }
        });
        jMenuBar1.add(menu_taikhoan);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(324, 324, 324)
                .addComponent(txt_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btn_timkiem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(destop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(destop))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_banhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_banhangActionPerformed
        // TODO add your handling code here:
        if (DangNhap.tkdadn == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng đăng nhập để xử dụng chức năng này");
        } else {
            destop.add(bh);
            tk.setVisible(true);
            bh.setVisible(false);
            gt.setVisible(false);
            sp.setVisible(false);
            tttk.setVisible(false);

        }
    }//GEN-LAST:event_menu_banhangActionPerformed

    private void menu_banhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_banhangMouseClicked
        // TODO add your handling code here:
        if (DangNhap.tkdadn == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng đăng nhập để xử dụng chức năng này");
        } else {
            destop.add(bh);
            tk.setVisible(true);
            gt.setVisible(false);
            sp.setVisible(false);
            bh.setVisible(true);
            tttk.setVisible(false);
        }
    }//GEN-LAST:event_menu_banhangMouseClicked

    private void menu_gioithieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_gioithieuActionPerformed
        // TODO add your handling code here:
//
//        destop.add(gt);
//        bh.setVisible(false);
//        sp.setVisible(false);
//        gt.setVisible(true);
//        tttk.setVisible(false);
    }//GEN-LAST:event_menu_gioithieuActionPerformed

    private void menu_gioithieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_gioithieuMouseClicked
        // TODO add your handling code here:
        if (DangNhap.tkdadn == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng đăng nhập để xử dụng chức năng này");
        } else {
            bh.setVisible(false);
            sp.setVisible(false);
            tk.setVisible(false);
            destop.add(gt);
            gt.setVisible(true);
            tttk.setVisible(false);
        }
    }//GEN-LAST:event_menu_gioithieuMouseClicked

    private void menu_sanphamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_sanphamMouseClicked
        // TODO add your handling code here:
        if (DangNhap.tkdadn == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng đăng nhập để xử dụng chức năng này");
        } else {
            bh.setVisible(false);
            gt.setVisible(false);
            tk.setVisible(false);
            destop.add(sp);
            tttk.setVisible(false);
            sp.setVisible(true);
        }
    }//GEN-LAST:event_menu_sanphamMouseClicked

    private void menu_trangchuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_trangchuMouseClicked
        // TODO add your handling code here:
        if (DangNhap.tkdadn == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng đăng nhập để xử dụng chức năng này");
        } else {
            sp.setVisible(false);
            bh.setVisible(false);
            tk.setVisible(false);
            gt.setVisible(false);
            tttk.setVisible(false);
        }
    }//GEN-LAST:event_menu_trangchuMouseClicked

    private void menu_taikhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_taikhoanMouseClicked
        // TODO add your handling code here:
        if (DangNhap.tkdadn == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng đăng nhập để xử dụng chức năng này");
        } else {
            sp.setVisible(false);
            tk.setVisible(false);
            bh.setVisible(false);
            gt.setVisible(false);
            destop.add(tttk);
            tttk.setVisible(true);
        }
    }//GEN-LAST:event_menu_taikhoanMouseClicked

    private void menu_sanphamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_sanphamActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_menu_sanphamActionPerformed

    private void menu_taikhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_taikhoanActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_menu_taikhoanActionPerformed

    private void btn_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timkiemActionPerformed
        // TODO add your handling code here:
        if (DangNhap.tkdadn == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng đăng nhập để xử dụng chức năng này");
        } else {
            timkiem();
            sp.setVisible(false);
            bh.setVisible(false);
            gt.setVisible(false);
            tttk.setVisible(false);
        }
    }//GEN-LAST:event_btn_timkiemActionPerformed
    public static String maspct = "";

    public void timkiem() {
        if (txt_timkiem.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên hoặc mã sản phẩm cần tìm");
            return;
        }
        tk.setVisible(false);
        try {
            String sql = "select * from sanpham where tensp like ? or masp like ? or tendanhmuc like ? or maspchitiet like ?";
            PreparedStatement pstm = con.prepareStatement(sql);
            pstm.setString(1, "%" + txt_timkiem.getText() + "%");
            pstm.setString(2, "%" + txt_timkiem.getText() + "%");
            pstm.setString(3, "%" + txt_timkiem.getText() + "%");
            pstm.setString(4, "%" + txt_timkiem.getText() + "%");
            ResultSet rs = pstm.executeQuery();
            list.clear();
            while (rs.next()) {
                maspct = rs.getString(2);
                Sanpham sp = new Sanpham(maspct);
                list.add(sp);
//                JOptionPane.showMessageDialog(this, "Đã tìm thấy sản phẩm");
                tk = new TimKiem(list);
             
            }
            destop.add(tk);
            tk.setVisible(true);
//            }else{
//                JOptionPane.showMessageDialog(this, "ko tìm thấy sản phẩm");
//            } 

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Không tìm được sản phẩm " + txt_timkiem.getText());
//            e.printStackTrace();
        }
        
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TrangchuNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TrangchuNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TrangchuNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TrangchuNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TrangchuNV().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_timkiem;
    private javax.swing.JDesktopPane destop;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lbl_banner;
    private javax.swing.JMenu menu_banhang;
    private javax.swing.JMenu menu_gioithieu;
    private javax.swing.JMenu menu_sanpham;
    private javax.swing.JMenu menu_taikhoan;
    private javax.swing.JMenu menu_trangchu;
    private javax.swing.JTextField txt_timkiem;
    // End of variables declaration//GEN-END:variables
}
