/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

import static Menu.DangNhap.tkdadn;
import Uhelper.Helper;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author khanh
 */
public class XoaNhanVien extends javax.swing.JInternalFrame {

    /**
     * Creates new form XoaNhanVien
     */
    DefaultTableModel model;
    Connection cn;
    int index;
    
    ThemNhanVien themnhanvien;
    
    public XoaNhanVien() {
        initComponents();
        cn=Helper.ketnoi("QLBH01");
        String header[]={"Tên tài khoản","Họ tên","Email","Số điện thoại","Vai trò"};
        String data[][]=null;
        model= new DefaultTableModel(data, header);
         
        loadTable();
    }

    
    public void loadTable(){
        try {
            String sql="Select * from taikhoan where vaitro =0 or vaitro=1";
            Statement stm= cn.createStatement();
            ResultSet rs=stm.executeQuery(sql);
            model.setRowCount(0);
            while (rs.next()) { 
                model.addRow(new Object[]{rs.getString(1),rs.getString(3),rs.getString(7),rs.getString(6),rs.getString(8)});
            }
            tbl_nhanvien.setModel(model);
            stm.close();
            rs.close();
        } catch (Exception e) {
//            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopnv = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_nhanvien = new javax.swing.JTable();
        btn_xoanv = new javax.swing.JButton();
        btn_themnv = new javax.swing.JButton();

        tbl_nhanvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbl_nhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_nhanvienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_nhanvien);

        btn_xoanv.setBackground(new java.awt.Color(255, 255, 255));
        btn_xoanv.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_xoanv.setText("Xóa nhân viên");
        btn_xoanv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoanvActionPerformed(evt);
            }
        });

        btn_themnv.setBackground(new java.awt.Color(255, 255, 255));
        btn_themnv.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_themnv.setText("Thêm nhân viên");
        btn_themnv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themnvActionPerformed(evt);
            }
        });

        desktopnv.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopnv.setLayer(btn_xoanv, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopnv.setLayer(btn_themnv, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopnvLayout = new javax.swing.GroupLayout(desktopnv);
        desktopnv.setLayout(desktopnvLayout);
        desktopnvLayout.setHorizontalGroup(
            desktopnvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopnvLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(desktopnvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1345, Short.MAX_VALUE)
                    .addGroup(desktopnvLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_xoanv, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btn_themnv, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(285, 285, 285)))
                .addContainerGap())
        );
        desktopnvLayout.setVerticalGroup(
            desktopnvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopnvLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addGroup(desktopnvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_themnv, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_xoanv, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopnv)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopnv)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_nhanvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_nhanvienMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tbl_nhanvienMouseClicked

    private void btn_xoanvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoanvActionPerformed
        // TODO add your handling code here:
        index= tbl_nhanvien.getSelectedRow();
        String vaitro = (String) tbl_nhanvien.getValueAt(index, 4);
        try {
            if (tbl_nhanvien.getRowCount() <= 0) {
                JOptionPane.showMessageDialog(this, "Không còn dữ liệu để xóa ");
                return;
            }
            
            if(index==-1){
                JOptionPane.showMessageDialog(this, "Vui lòng chọn nhân viên để xóa");
                return;
            }
            int hoi = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa?", "Xóa", JOptionPane.YES_NO_OPTION);
            if(vaitro.equalsIgnoreCase("1")){
                JOptionPane.showMessageDialog(this, "Không xóa ");
                return;
            }
             if (hoi != JOptionPane.YES_OPTION) {
                return;
            }else{
            model.removeRow(index);
            String sql = "Update taikhoan\n"
                    + "set vaitro=2\n"
                    + "where tentaikhoan=?";
            PreparedStatement pstm = cn.prepareStatement(sql);
            pstm.setString(1, (String)tbl_nhanvien.getValueAt(index,0));
            int row = pstm.executeUpdate();
            if (row > 0) {
                JOptionPane.showMessageDialog(this, "Xóa thành công");
//                FillToTable();
                index--;
            } else {
                JOptionPane.showMessageDialog(this, "Xóa thất bại");
            }
            pstm.close();
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Xóa thành công");
//            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_xoanvActionPerformed

    private void btn_themnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themnvActionPerformed
        // TODO add your handling code here:
        if (themnhanvien == null || themnhanvien.isClosed()) {
            themnhanvien = new ThemNhanVien();
            loadTable();
            desktopnv.add(themnhanvien);
            themnhanvien.setVisible(true);
        } else {
            themnhanvien.setVisible(true);
        }
    }//GEN-LAST:event_btn_themnvActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_themnv;
    private javax.swing.JButton btn_xoanv;
    private javax.swing.JDesktopPane desktopnv;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_nhanvien;
    // End of variables declaration//GEN-END:variables

 
}
