/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Truong Dep Zai
 */
public class Bai1_2 extends javax.swing.JFrame {

    Vector Header = new Vector();
    Vector Data = new Vector();

    public Bai1_2() {
        initComponents();
//        Header.add("ID");
//        Header.add("FULLNAME");
//        Header.add("COUNTRY");
//        Header.add("GENDER");
//        Header.add("STATUS");
//
//        Vector vctRow1 = new Vector();
//        vctRow1.add("NV01");
//        vctRow1.add("Nguyễn Nghiệm");
//        vctRow1.add("Việt Nam");
//        vctRow1.add("Male");
//        vctRow1.add("Married");
//        Data.add(vctRow1);
//
//        Vector vctRow2 = new Vector();
//        vctRow2.add("NV02");
//        vctRow2.add("Lê Thị Phương Thảo");
//        vctRow2.add("Singapore");
//        vctRow2.add("female");
//        vctRow2.add("Married");
//        Data.add(vctRow2);
//
//        Vector vctRow3 = new Vector();
//        vctRow3.add("NV03");
//        vctRow3.add("Nguyễn Đình Thiên Long");
//        vctRow3.add("United States");
//        vctRow3.add("Male");
//        vctRow3.add("Single");
//        Data.add(vctRow3);
//
//        Vector vctRow4 = new Vector();
//        vctRow4.add("NV04");
//        vctRow4.add("Nguyễn Đinh Hoàng Long");
//        vctRow4.add("Mlaysia");
//        vctRow4.add("Male");
//        vctRow4.add("Single");
//        Data.add(vctRow4);
//
//        tbl_StaffList.setModel(new DefaultTableModel(Data, Header));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_StaffList = new javax.swing.JTable();
        jtable1 = new javax.swing.JLabel();
        btn_Load = new javax.swing.JButton();
        btn_Store = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl_StaffList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Fullname", "Country", "Status"
            }
        ));
        jScrollPane1.setViewportView(tbl_StaffList);

        jtable1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtable1.setForeground(new java.awt.Color(0, 0, 255));
        jtable1.setText("Staff List");

        btn_Load.setText("Load");
        btn_Load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LoadActionPerformed(evt);
            }
        });

        btn_Store.setText("Store");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(332, Short.MAX_VALUE)
                .addComponent(btn_Load)
                .addGap(18, 18, 18)
                .addComponent(btn_Store)
                .addGap(260, 260, 260))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jtable1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jtable1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Load)
                    .addComponent(btn_Store))
                .addGap(199, 199, 199))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_LoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LoadActionPerformed
        // TODO add your handling code here:
         Header.add("ID");
        Header.add("FULLNAME");
        Header.add("COUNTRY");
        Header.add("GENDER");
        Header.add("STATUS");

        Vector vctRow1 = new Vector();
        vctRow1.add("NV01");
        vctRow1.add("Nguyễn Nghiệm");
        vctRow1.add("Việt Nam");
        vctRow1.add("Male");
        vctRow1.add("Married");
        Data.add(vctRow1);

        Vector vctRow2 = new Vector();
        vctRow2.add("NV02");
        vctRow2.add("Lê Thị Phương Thảo");
        vctRow2.add("Singapore");
        vctRow2.add("female");
        vctRow2.add("Married");
        Data.add(vctRow2);

        Vector vctRow3 = new Vector();
        vctRow3.add("NV03");
        vctRow3.add("Nguyễn Đình Thiên Long");
        vctRow3.add("United States");
        vctRow3.add("Male");
        vctRow3.add("Single");
        Data.add(vctRow3);

        Vector vctRow4 = new Vector();
        vctRow4.add("NV04");
        vctRow4.add("Nguyễn Đinh Hoàng Long");
        vctRow4.add("Mlaysia");
        vctRow4.add("Male");
        vctRow4.add("Single");
        Data.add(vctRow4);

        tbl_StaffList.setModel(new DefaultTableModel(Data, Header));
        
    }//GEN-LAST:event_btn_LoadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bai1_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bai1_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bai1_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bai1_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bai1_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Load;
    private javax.swing.JButton btn_Store;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jtable1;
    private javax.swing.JTable tbl_StaffList;
    // End of variables declaration//GEN-END:variables

}
