/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import DAO.*;
import Model.Type;

import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * @author ma-user
 */
public class M extends javax.swing.JPanel {

    /**
     * Creates new form M
     */
    public M() {
        initComponents();
        lblUser.setText(Main.logged ? Main.account.getUser() : "");
        lblSoLuong.setText(new ProductDAO().getAllNumOfPhoneInStorage() == -1 ?
                "Lỗi đọc" : String.valueOf(new ProductDAO().getAllNumOfPhoneInStorage()));
        Date NG = new ImportDAO().getNearestImportDate();
        lblNhapgan.setText(NG == null ? "Không có" : (new SimpleDateFormat("MMM dd,yyyy - hh:mm:ss")).format(NG));

        Date XG = new ExportDAO().getNearestExportDate();
        lblXuatgan.setText(XG == null ? "Không có" : (new SimpleDateFormat("MMM dd,yyyy - hh:mm:ss")).format(XG));
        String id = new TypeDAO().getRemainType();
        lblTonkho.setText(id == null ? "Không có" : new TypeDAO().select(new Type(id, "", "")).getType_name());
        id = new TypeDAO().getNearestType();
        lblBangan.setText(id == null ? "Không có" : new TypeDAO().select(new Type(id, "", "")).getType_name());
        Integer sln = new ImportDAO().getThisMonthImportCount();
        lblSonhap.setText(sln == null ? "Không có" : String.valueOf(sln));
        lblSoluongthang.setText(String.valueOf(new Import_DetailDAO().getMonthImportCount()));
        lblSoxuat.setText(String.valueOf(new Export_DetailDAO().getMonthExportCount()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblNhapgan = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblXuatgan = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblTonkho = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblBangan = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblSonhap = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblSoluongthang = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblSoxuat = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblSoLuong = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("QUẢN LÝ XUẤT NHẬP KHO");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Đang đăng nhập:");

        lblUser.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 153, 0));
        lblUser.setText(".........");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Lần nhập kho gần nhất:");

        lblNhapgan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblNhapgan.setForeground(new java.awt.Color(255, 153, 0));
        lblNhapgan.setText(".........");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Lần xuất kho gần nhất:");

        lblXuatgan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblXuatgan.setForeground(new java.awt.Color(255, 153, 0));
        lblXuatgan.setText(".........");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Sản phẩm tồn kho lâu nhất:");

        lblTonkho.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTonkho.setForeground(new java.awt.Color(255, 153, 0));
        lblTonkho.setText(".........");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Sản phẩm xuất kho gần nhất:");

        lblBangan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblBangan.setForeground(new java.awt.Color(255, 153, 0));
        lblBangan.setText(".........");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Số lần nhập kho trong tháng:");

        lblSonhap.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSonhap.setForeground(new java.awt.Color(255, 153, 0));
        lblSonhap.setText(".........");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Số sản phẩm nhập trong tháng");

        lblSoluongthang.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSoluongthang.setForeground(new java.awt.Color(255, 153, 0));
        lblSoluongthang.setText(".........");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Số sản phẩm xuất trong tháng");

        lblSoxuat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSoxuat.setForeground(new java.awt.Color(255, 153, 0));
        lblSoxuat.setText(".........");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Số lượng sản phẩm trong kho:");

        lblSoLuong.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSoLuong.setForeground(new java.awt.Color(255, 153, 0));
        lblSoLuong.setText(".........");

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LIB/ICON/Exit.png"))); // NOI18N
        btnExit.setText("Đăng xuất");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(363, 363, 363)
                                                .addComponent(jLabel1))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(148, 148, 148)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(lblTonkho, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(lblXuatgan, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(lblNhapgan, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(lblSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(140, 140, 140)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(lblSoluongthang, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(lblSoxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(lblSonhap, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(lblBangan, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addContainerGap(253, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnExit)
                                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel1)
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(lblUser))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel10)
                                        .addComponent(lblSoLuong))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(lblNhapgan))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(lblXuatgan))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(lblTonkho))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(lblBangan))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(lblSonhap))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8)
                                        .addComponent(lblSoluongthang))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel9)
                                        .addComponent(lblSoxuat))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                .addComponent(btnExit)
                                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        Main.account = null;
        Main.logged = false;

    }//GEN-LAST:event_btnExitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblBangan;
    private javax.swing.JLabel lblNhapgan;
    private javax.swing.JLabel lblSoLuong;
    private javax.swing.JLabel lblSoluongthang;
    private javax.swing.JLabel lblSonhap;
    private javax.swing.JLabel lblSoxuat;
    private javax.swing.JLabel lblTonkho;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblXuatgan;
    // End of variables declaration//GEN-END:variables
}
