/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Helper.Helper;
import Model.Account;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

import static Helper.Helper.showPanel;

/**
 *
 * @author ma-user
 */
public class Main extends javax.swing.JFrame {

    public static Account account;
    public static boolean logged = false;
    public Thread t1 = new Thread(new Runnable() {
        @Override
        public void run() {
            while (true) {
                if (logged == false) {
                    showLG();
                }
                try {
                    Thread.sleep(1000);
                    long i = 0;
                    System.out.printf("%d", ++i);
                } catch (Exception e) {
                }
            }
        }
    });

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
//        setSize(new Dimension(1366, 800));
        if (Helper.openConnection() == false) {
            JOptionPane.showMessageDialog(this, "Xảy ra lỗi. Xin mời chạy lại.");
        }
        t1.start();
        settime();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnMain = new javax.swing.JToggleButton();
        btnNK = new javax.swing.JToggleButton();
        btnXK = new javax.swing.JToggleButton();
        btnNCC = new javax.swing.JToggleButton();
        btnMSP = new javax.swing.JToggleButton();
        btnQLK = new javax.swing.JToggleButton();
        btnTK = new javax.swing.JToggleButton();
        btnTDTT = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        rootP = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ XUẤT NHẬP KHO");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buttonGroup1.add(btnMain);
        btnMain.setText("CHƯƠNG TRÌNH");
        btnMain.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnMainItemStateChanged(evt);
            }
        });

        buttonGroup1.add(btnNK);
        btnNK.setText("NHẬP KHO");
        btnNK.setEnabled(false);
        btnNK.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnNKItemStateChanged(evt);
            }
        });

        buttonGroup1.add(btnXK);
        btnXK.setText("XUẤT KHO");
        btnXK.setEnabled(false);
        btnXK.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnXKItemStateChanged(evt);
            }
        });

        buttonGroup1.add(btnNCC);
        btnNCC.setText("NHÀ CUNG CẤP");
        btnNCC.setEnabled(false);
        btnNCC.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnNCCItemStateChanged(evt);
            }
        });

        buttonGroup1.add(btnMSP);
        btnMSP.setText("MÃ SẢN PHẨM");
        btnMSP.setEnabled(false);
        btnMSP.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnMSPItemStateChanged(evt);
            }
        });

        buttonGroup1.add(btnQLK);
        btnQLK.setText("QUẢN LÝ KỆ");
        btnQLK.setEnabled(false);
        btnQLK.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnQLKItemStateChanged(evt);
            }
        });

        buttonGroup1.add(btnTK);
        btnTK.setText("TÌM KIẾM");
        btnTK.setEnabled(false);
        btnTK.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnTKItemStateChanged(evt);
            }
        });

        buttonGroup1.add(btnTDTT);
        btnTDTT.setText("THAY ĐỔI TRẠNG THÁI");
        btnTDTT.setEnabled(false);
        btnTDTT.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnTDTTItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNCC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQLK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTDTT, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMain)
                .addGap(18, 18, 18)
                .addComponent(btnNK)
                .addGap(18, 18, 18)
                .addComponent(btnXK)
                .addGap(18, 18, 18)
                .addComponent(btnNCC)
                .addGap(18, 18, 18)
                .addComponent(btnMSP)
                .addGap(18, 18, 18)
                .addComponent(btnQLK)
                .addGap(18, 18, 18)
                .addComponent(btnTK)
                .addGap(18, 18, 18)
                .addComponent(btnTDTT)
                .addContainerGap(370, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        lblUser.setText("Admin");

        lblTime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTime.setText("Time");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 744, Short.MAX_VALUE)
                .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout rootPLayout = new javax.swing.GroupLayout(rootP);
        rootP.setLayout(rootPLayout);
        rootPLayout.setHorizontalGroup(
            rootPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1144, Short.MAX_VALUE)
        );
        rootPLayout.setVerticalGroup(
            rootPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(rootP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rootP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMainItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnMainItemStateChanged
        // TODO add your handling code here:
        if (btnMain.isSelected()) {
            M m = new M();
            showPanel(m);
        }
    }//GEN-LAST:event_btnMainItemStateChanged

    private void btnNKItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnNKItemStateChanged
        // TODO add your handling code here:
        if (btnNK.isSelected()) {
            NK m = new NK();
            showPanel(m);
        }
    }//GEN-LAST:event_btnNKItemStateChanged

    private void btnXKItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnXKItemStateChanged
        // TODO add your handling code here:
        if (btnXK.isSelected()) {
            XK m = new XK();
            showPanel(m);
        }
    }//GEN-LAST:event_btnXKItemStateChanged

    private void btnNCCItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnNCCItemStateChanged
        // TODO add your handling code here:
        if (btnNCC.isSelected()) {
            NCC m = new NCC();
            showPanel(m);
        }
    }//GEN-LAST:event_btnNCCItemStateChanged

    private void btnMSPItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnMSPItemStateChanged
        // TODO add your handling code here:
        if (btnMSP.isSelected()) {
            MSP m = new MSP();
            showPanel(m);
        }
    }//GEN-LAST:event_btnMSPItemStateChanged

    private void btnQLKItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnQLKItemStateChanged
        // TODO add your handling code here:
        if (btnQLK.isSelected()) {
            QLK m = new QLK();
            showPanel(m);
        }
    }//GEN-LAST:event_btnQLKItemStateChanged

    private void btnTKItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnTKItemStateChanged
        // TODO add your handling code here:
        if (btnTK.isSelected()) {
            TK m = new TK();
            showPanel(m);
        }
    }//GEN-LAST:event_btnTKItemStateChanged

    private void btnTDTTItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnTDTTItemStateChanged
        // TODO add your handling code here:
        if (btnTDTT.isSelected()) {
            TDTT m = new TDTT();
            showPanel(m);
        }
    }//GEN-LAST:event_btnTDTTItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnMSP;
    private javax.swing.JToggleButton btnMain;
    private javax.swing.JToggleButton btnNCC;
    private javax.swing.JToggleButton btnNK;
    private javax.swing.JToggleButton btnQLK;
    private javax.swing.JToggleButton btnTDTT;
    private javax.swing.JToggleButton btnTK;
    private javax.swing.JToggleButton btnXK;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblUser;
    public static javax.swing.JPanel rootP;
    // End of variables declaration//GEN-END:variables

    private void settime() {
        Thread t = new Thread(new Runnable() {
            @Override
            public void run() {
                while (true) {
                    SimpleDateFormat sdf = new SimpleDateFormat("MMM dd yyyy - hh:mm:ss");
                    lblTime.setText(sdf.format(Date.from(LocalDateTime.now().atZone(ZoneId.systemDefault()).toInstant())));
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {
                    }
                }
            }
        });
        t.start();
    }

    public void showLG() {
        Login lg = new Login(this, true);
        lg.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent we) {
                if (logged == false) {
                    System.exit(0);
                }
                setMenuState(logged);
                btnMain.setSelected(true);
            }
        });
        lg.setVisible(true);
    }

    private void setMenuState(boolean logged) {
        btnNK.setEnabled(logged);
        btnXK.setEnabled(logged);
        btnNCC.setEnabled(logged && account.getRole().equalsIgnoreCase("QL"));
        btnMSP.setEnabled(logged && account.getRole().equalsIgnoreCase("QL"));
        btnQLK.setEnabled(logged && account.getRole().equalsIgnoreCase("QL"));
        btnTK.setEnabled(logged);
        btnTDTT.setEnabled(logged);
        lblUser.setText(logged ? account.getUser() : "");
    }

//    private void showPanel(JPanel panel) {
//        rootP.removeAll();
//        javax.swing.GroupLayout rootPLayout = new javax.swing.GroupLayout(rootP);
//        rootP.setLayout(rootPLayout);
//        rootPLayout.setHorizontalGroup(
//                rootPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addComponent(panel)
//        );
//        rootPLayout.setVerticalGroup(
//                rootPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addComponent(panel)
//        );
//    }

}
