/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.QLDT;

import GUI.Main;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.event.InternalFrameAdapter;
import javax.swing.event.InternalFrameEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ma-user
 */
public class XemDT extends javax.swing.JInternalFrame {

    int index;
    ArrayList<DienThoai_Class> lst = new ArrayList<>();
    DefaultTableModel model;
    DecimalFormat df = new DecimalFormat("#.###");
    public static String ID, name, Ram1, BoNHoTrong1, Details1, Cam1, TSKT1, GiaBan1, sl;

    /**
     * Creates new form ThemDT
     */
    public XemDT() {
        initComponents();
        setClosable(true);
//        addInternalFrameListener(new InternalFrameAdapter() {
//            @Override
//            public void internalFrameClosed(InternalFrameEvent e) {
//                Main.showMDI();
//            }
//        });
        lst = Helper.PhoneHelper.getListPhone();
        model = (DefaultTableModel) tbl_DT.getModel();

        Showtable();
    }

    public void showDetail(int i) {
        if (i >= 0) {
//            model.setRowCount(0);
            // SoLuong=(String) tbl_Phone.getValueAt(2, i);
//            txtCode.setText(lst.get(i).MaDT);
//            txtTen.setText(lst.get(i).TenDT);
//            txtSL.setText(String.valueOf(lst.get(i).SoLuong));
//            txtGiaban.setText(df.format(lst.get(i).GiaBan));
            txtTSKT.setText("ID: " + lst.get(index).MaDT + "\n"
                    + "Cam: " + lst.get(index).cam + "\n"
                    + "name: " + lst.get(index).TenDT + "\n"
                    + "Bộ nhớ: " + lst.get(index).BoNHoTrong + "\n"
                    + "ram: " + lst.get(index).Ram + "\n"
                    + "amount: " + String.valueOf(lst.get(index).SoLuong) + "\n"
                    + "sell_price: " + df.format(lst.get(index).GiaBan) + "\n"
                    + "details: " + lst.get(index).Details + "\n");
//                    + "thông tin thêm: " + lst.get(index).Details + "\n");

            ID = lst.get(i).MaDT;
            name = lst.get(i).TenDT;
            sl = String.valueOf(lst.get(i).SoLuong);
            GiaBan1 = String.valueOf(lst.get(i).GiaBan);
            Cam1 = lst.get(i).cam;
            Ram1 = lst.get(0).Ram;
            BoNHoTrong1 = lst.get(0).BoNHoTrong;
            Details1 = lst.get(0).Details;

            tbl_DT.setRowSelectionInterval(i, i);

        }
    }

    public void Showtable() {
        model.setRowCount(0);
        for (DienThoai_Class dt : lst) {
            model.addRow(new Object[]{
                dt.getMaDT(), dt.getTenDT(), dt.getSoLuong(), dt.getBoNHoTrong(), dt.getCam(), dt.getDetails(),
                dt.getGiaBan(),
                dt.getRam()
            });
        };
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTSKT = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_DT = new javax.swing.JTable();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chi tiết", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        txtTSKT.setColumns(20);
        txtTSKT.setRows(5);
        txtTSKT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTSKTMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(txtTSKT);

        tbl_DT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "amount", "sell_price", "details", "cam", "ram", "rom"
            }
        ));
        tbl_DT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_DTMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_DT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnXoa)
                            .addComponent(btnSua))
                        .addGap(68, 68, 68))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int row = tbl_DT.getSelectedRow();
        if (row >= 0 && JOptionPane.showConfirmDialog(this, "bạn có muốn xóa khong") == JOptionPane.YES_OPTION) {
            DienThoai_Class sv = new DienThoai_Class();

            sv.setMaDT((String) model.getValueAt(row, 0));
            model.removeRow(row);
            Helper.PhoneHelper.deleteDT(sv);
            Helper.PhoneHelper.getListPhone();
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tbl_DTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_DTMouseClicked
        // TODO add your handling code here:
        index = tbl_DT.getSelectedRow();
        showDetail(index);


    }//GEN-LAST:event_tbl_DTMouseClicked

    private void txtTSKTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTSKTMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTSKTMouseClicked

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        ThemDT tdt = new ThemDT();
        tdt.setTitle("Đăng Nhập");
        Main.rootPanel.add(tdt);
//        tdt.setLocation(this.getWidth() / 2 - tdt.getWidth() / 2, (this.getHeight() - 10) / 2 - tdt.getHeight() / 2 - 20);
        tdt.setVisible(true);
    }//GEN-LAST:event_btnSuaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTable tbl_DT;
    private javax.swing.JTextArea txtTSKT;
    // End of variables declaration//GEN-END:variables
}
