/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laydiemjava3;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Truong Dep Zai
 */
public class NewJFrame1 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    public NewJFrame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_ShowLove = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_ShowLove.setText("ShowLove");
        btn_ShowLove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ShowLoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(btn_ShowLove)
                .addContainerGap(267, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btn_ShowLove)
                .addContainerGap(245, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ShowLoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ShowLoveActionPerformed
        // TODO add your handling code here:
         String option[] = {"Có ","Không","Một lần","Hai lần","Lớn hơn 3 lần"};
         ImageIcon icon = new ImageIcon("C:\\Users\\Truong Dep Zai\\Desktop\\Images\\Images\\Heart.png");
       int chon =  JOptionPane.showOptionDialog(this, "Bạn đã có người yêu chưa", "Tiêu đề",
               JOptionPane.YES_NO_OPTION,
               JOptionPane.INFORMATION_MESSAGE, icon, option, option[2]);
       
       if(chon == 0 ){
           JOptionPane.showMessageDialog(this, option[0], "Thông Báo", JOptionPane.INFORMATION_MESSAGE, icon);
       }else if(chon == 1){
             JOptionPane.showMessageDialog(this, option[1], "Thông Báo", JOptionPane.INFORMATION_MESSAGE, icon);
       }else if(chon == 2){
            JOptionPane.showMessageDialog(this, option[2], "Thông Báo", JOptionPane.INFORMATION_MESSAGE, icon);
       }else if(chon == 3){
            JOptionPane.showMessageDialog(this, option[3], "Thông Báo", JOptionPane.INFORMATION_MESSAGE, icon);
       }else{
            JOptionPane.showMessageDialog(this, option[4], "Thông Báo", JOptionPane.INFORMATION_MESSAGE, icon);
       }
    }//GEN-LAST:event_btn_ShowLoveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ShowLove;
    // End of variables declaration//GEN-END:variables
}
